{{- if and .Values.certGenerator.enabled .Values.certGenerator.rbac.create (not .Values.webhook.tls.existingSecret) (not .Values.webhook.tls.certPEM) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubetrust.fullname" . }}-certgen
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubetrust.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubetrust.fullname" . }}-certgen
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubetrust.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubetrust.fullname" . }}-certgen
subjects:
- kind: ServiceAccount
  name: {{ include "kubetrust.certgen.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
