{{- if and .Values.certGenerator.enabled (not .Values.webhook.tls.existingSecret) (not .Values.webhook.tls.certPEM) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubetrust.certgen.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubetrust.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
{{- end }}
