{{- if and (not .Values.webhook.tls.existingSecret) .Values.webhook.tls.certPEM .Values.webhook.tls.keyPEM }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubetrust.webhookTLSSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubetrust.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  {{ .Values.webhook.tls.certKey }}: {{ .Values.webhook.tls.certPEM | b64enc }}
  {{ .Values.webhook.tls.keyKey }}: {{ .Values.webhook.tls.keyPEM | b64enc }}
  {{- if .Values.webhook.tls.caPEM }}
  {{ .Values.webhook.tls.caKey }}: {{ .Values.webhook.tls.caPEM | b64enc }}
  {{- end }}
{{- end }}
