apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubetrust.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubetrust.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webhook.service.type }}
  publishNotReadyAddresses: true
  ports:
  - port: {{ .Values.webhook.service.port }}
    targetPort: {{ .Values.webhook.service.targetPort }}
    protocol: TCP
    name: https
  selector:
    {{- include "kubetrust.selectorLabels" . | nindent 4 }}
