apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kubetrust.fullname" . }}
  labels:
    {{- include "kubetrust.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
webhooks:
- name: {{ include "kubetrust.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  clientConfig:
    {{- if .Values.webhook.tls.caPEM }}
    caBundle: {{ .Values.webhook.tls.caPEM | b64enc }}
    {{- else }}
    caBundle: {{ .Values.webhook.tls.caPEM }}
    {{- end }}
    service:
      name: {{ include "kubetrust.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: "/mutate"
      port: {{ .Values.webhook.service.port }}
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  - operations: ["CREATE"]
    apiGroups: ["batch"]
    apiVersions: ["v1"]
    resources: ["jobs"]
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
  timeoutSeconds: 5
  reinvocationPolicy: Never
  failurePolicy: Ignore
  namespaceSelector:
    {{- toYaml .Values.webhook.namespaceSelector | nindent 4 }}
